version: "3.3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: skedway_db
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-compose/sql:/docker-entrypoint-initdb.d

volumes:
  db-data: